theme: jekyll-theme-cayman
title: 'April 2019 MCA Workshop @ ESALQ'
description: 'Piricicaba, State of Sao Paolo, Brazil'
date: 'April 22nd-25nd, 2018'
github:
  repository_url: https://ucdavis-bioinformatics-training.github.io/2019_April_ESALQ_Microbial_Community_Analysis/
